from django.db import models

from common.mixins import AutoStrMixin


class InverterDataPoint(AutoStrMixin, models.Model):
    class Meta:
        db_table = "inverter_data_points"
        app_label = "mytools"

    idp_date = models.DateField(unique=True)
    idp_solar_generation_kwh = models.FloatField(
        help_text="Energy generated by solar panels"
    )
    idp_grid_export_kwh = models.FloatField(help_text="Energy sent to the grid")
    idp_grid_import_kwh = models.FloatField(help_text="Energy pulled from the grid")
    idp_home_consumption_kwh = models.FloatField(
        help_text="Total energy used by the house"
    )
    idp_battery_charge_kwh = models.FloatField()
    idp_battery_discharge_kwh = models.FloatField()
