# Generated by Django 5.2.6 on 2025-12-19 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discord", "0004_alter_youtubesong_ys_playlist"),
    ]

    operations = [
        migrations.CreateModel(
            name="MinecraftServer",
            fields=[
                ("mcs_id", models.AutoField(primary_key=True, serialize=False)),
                ("mcs_name", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "minecraft_servers",
            },
        ),
        migrations.CreateModel(
            name="MinecraftPlayer",
            fields=[
                ("mp_id", models.AutoField(primary_key=True, serialize=False)),
                ("mp_uuid", models.UUIDField()),
                ("mp_mc_name", models.CharField(max_length=255)),
                (
                    "mp_ds_user_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "mp_ds_server",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "mp_mcs_server",
                    models.ForeignKey(
                        db_column="mp_mcs_server_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="discord.minecraftserver",
                    ),
                ),
            ],
            options={
                "db_table": "minecraft_players",
            },
        ),
        migrations.CreateModel(
            name="MinecraftStat",
            fields=[
                ("mst_id", models.AutoField(primary_key=True, serialize=False)),
                ("mst_data", models.JSONField()),
                ("mst_timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "mst_player",
                    models.ForeignKey(
                        db_column="mst_player_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stats",
                        to="discord.minecraftplayer",
                    ),
                ),
            ],
            options={
                "db_table": "minecraft_stats",
            },
        ),
    ]
