# Generated by Django 5.2.6 on 2025-12-14 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discord", "0004_alter_youtubesong_ys_playlist"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="queueinterval",
            name="qi_at",
        ),
        migrations.RemoveField(
            model_name="queueinterval",
            name="qi_channel",
        ),
        migrations.AddField(
            model_name="queueinterval",
            name="qi_channel_id",
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name="queueinterval",
            name="qi_day_of_month",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="queueinterval",
            name="qi_quild_id",
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name="queueinterval",
            name="qi_schedule_type",
            field=models.CharField(
                choices=[
                    ("interval", "Every X minutes"),
                    ("daily", "Daily at specific time"),
                    ("weekly", "Weekly on specific day(s)"),
                    ("monthly", "Monthly on specific day"),
                ],
                default=None,
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="queueinterval",
            name="qi_time",
            field=models.TimeField(default=None),
        ),
        migrations.AddField(
            model_name="queueinterval",
            name="qi_weekday",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="queuepicture",
            name="qp_image",
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name="queuepicture",
            name="qp_interval",
            field=models.ForeignKey(
                db_column="qp_interval_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pictures",
                to="discord.queueinterval",
            ),
        ),
    ]
