# Generated by Django 5.2.6 on 2025-12-19 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("discord", "0005_minecraftserver_minecraftplayer_minecraftstat"),
    ]

    operations = [
        migrations.RenameField(
            model_name="minecraftplayer",
            old_name="mp_ds_server",
            new_name="mp_ds_quild_id",
        ),
    ]
