# Generated by Django 5.2.6 on 2025-12-14 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discord", "0005_remove_queueinterval_qi_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="queueinterval",
            name="qi_channel_id",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="queueinterval",
            name="qi_quild_id",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="queueinterval",
            name="qi_schedule_type",
            field=models.CharField(
                choices=[
                    ("interval", "Every X minutes"),
                    ("daily", "Daily at specific time"),
                    ("weekly", "Weekly on specific day(s)"),
                    ("monthly", "Monthly on specific day"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="queueinterval",
            name="qi_time",
            field=models.TimeField(),
        ),
    ]
