# Generated by Django 5.2.6 on 2025-12-14 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discord", "0006_alter_queueinterval_qi_channel_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="queueinterval",
            name="qi_interval_minutes",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="queueinterval",
            name="qi_created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="queueinterval",
            name="qi_time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
