# Generated by Django 5.2.6 on 2025-12-19 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discord", "0006_rename_mp_ds_server_minecraftplayer_mp_ds_quild_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="minecraftstat",
            name="mst_player",
            field=models.OneToOneField(
                db_column="mst_player_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stat",
                to="discord.minecraftplayer",
            ),
        ),
    ]
