# Generated by Django 5.2.6 on 2025-12-29 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discord", "0007_alter_minecraftstat_mst_player"),
    ]

    operations = [
        migrations.AlterField(
            model_name="minecraftstat",
            name="mst_timestamp",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
