services:
  web:
    image: backbone:latest
    container_name: backbone_web
    env_file:
      - .env.prod
    ports:
      - "127.0.0.1:8000:8000"
    volumes:
      - backbone_db:/app/databases
      - ./staticfiles:/app/staticfiles
      - backbone_media:/app/media
    security_opt:
      - seccomp=unconfined
    command: >
      sh -c "
        python manage.py migrate &&
        python manage.py migrate --database=discord_db &&
        python manage.py migrate --database=extension_db &&
        python manage.py migrate --database=mytools_db &&
        python manage.py collectstatic --noinput &&
        gunicorn backbone.wsgi:application --bind 0.0.0.0:8000"
    depends_on:
      - redis
    restart: unless-stopped

  worker:
    image: backbone:latest
    container_name: backbone_worker
    volumes:
      - backbone_db:/app/databases
      - backbone_media:/app/media
    env_file:
      - .env.prod
    command: celery -A backbone worker -l info -c 1
    depends_on:
      - redis
    restart: unless-stopped

  beat:
    image: backbone:latest
    container_name: backbone_beat
    env_file:
      - .env.prod
    volumes:
      - backbone_db:/app/databases
    command: celery -A backbone beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    depends_on:
      - redis
      - web
    restart: unless-stopped

  redis:
    image: arm32v7/redis:6.0.6
    container_name: backbone_redis
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - backbone_redis_data:/data
    command: redis-server
    restart: unless-stopped

volumes:
  backbone_redis_data:
    external: true
  backbone_media:
    external: true
  backbone_db:
    external: true
