services:
  web:
    build: .
    command: gunicorn backbone.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - ./databases:/app/databases
      - ./staticfiles:/app/staticfiles
    env_file:
      - .env.prod
    depends_on:
      - redis

  worker:
    build: .
    command: celery -A backbone worker -l info --pool=solo
    depends_on:
      - redis

  beat:
    build: .
    command: celery -A backbone beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    depends_on:
      - redis
      - web
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
