# Generated by Django 5.2.6 on 2025-10-04 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="apptoken",
            old_name="app_name",
            new_name="at_app_name",
        ),
        migrations.RenameField(
            model_name="apptoken",
            old_name="app_token",
            new_name="at_app_token",
        ),
        migrations.RenameField(
            model_name="apptoken",
            old_name="created_at",
            new_name="at_created_at",
        ),
        migrations.RenameField(
            model_name="apptoken",
            old_name="is_active",
            new_name="at_is_active",
        ),
    ]
