# Generated by Django 5.2.6 on 2025-10-09 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0002_rename_app_name_apptoken_at_app_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apptoken",
            name="at_app_token",
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
