# Generated by Django 5.2.6 on 2025-11-17 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discord", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="YoutubePlaylist",
            fields=[
                ("yp_id", models.AutoField(primary_key=True, serialize=False)),
                ("yp_name", models.CharField(max_length=255)),
                ("yp_user_id", models.TextField()),
                ("yp_guild_id", models.TextField()),
            ],
            options={
                "db_table": "youtube_playlist",
            },
        ),
        migrations.RenameModel(
            old_name="QueueIntervals",
            new_name="QueueInterval",
        ),
        migrations.RenameModel(
            old_name="QueuePictures",
            new_name="QueuePicture",
        ),
        migrations.RenameField(
            model_name="queuepicture",
            old_name="qp_interval_id",
            new_name="qp_interval",
        ),
        migrations.CreateModel(
            name="YoutubeSong",
            fields=[
                ("ys_id", models.AutoField(primary_key=True, serialize=False)),
                ("ys_url", models.TextField()),
                (
                    "ys_playlist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="discord.youtubeplaylist",
                    ),
                ),
            ],
            options={
                "db_table": "youtube_song",
            },
        ),
    ]
