# Generated by Django 5.2.6 on 2025-11-23 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "discord",
            "0002_youtubeplaylist_rename_queueintervals_queueinterval_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="youtubesong",
            name="ys_playlist",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="playlist_songs",
                to="discord.youtubeplaylist",
            ),
        ),
    ]
