# Generated by Django 5.2.6 on 2025-10-01 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="YoutubePlaylist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("yp_name", models.CharField(max_length=255)),
                ("yp_videos", models.JSONField()),
            ],
            options={
                "db_table": "youtube_playlist",
            },
        ),
    ]
