# Generated by Django 5.2.6 on 2025-12-29 15:16

import django.db.models.deletion
import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Etf",
            fields=[
                ("ef_id", models.AutoField(primary_key=True, serialize=False)),
                ("ef_name", models.CharField(max_length=255)),
                ("ef_isin", models.CharField(max_length=255)),
                ("ef_symbol", models.CharField(max_length=255)),
                (
                    "ef_distribution",
                    models.CharField(
                        choices=[("monthly", "Monthly"), ("quarterly", "Quarterly")],
                        max_length=10,
                    ),
                ),
            ],
            options={
                "db_table": "etfs",
            },
        ),
        migrations.CreateModel(
            name="EtfShare",
            fields=[
                ("efs_id", models.AutoField(primary_key=True, serialize=False)),
                ("efs_amount", models.FloatField()),
                ("efs_total_price", models.FloatField()),
                ("efs_purchase_date", models.DateField()),
                ("efs_created_at", models.DateField(auto_now_add=True)),
                (
                    "efs_ef",
                    models.ForeignKey(
                        db_column="efs_ef_id",
                        on_delete=django.db.models.expressions.Case,
                        related_name="efs",
                        to="mytools.etf",
                    ),
                ),
            ],
            options={
                "db_table": "etf_shares",
            },
        ),
        migrations.CreateModel(
            name="EtfEven",
            fields=[
                ("ee_id", models.AutoField(primary_key=True, serialize=False)),
                ("ee_ex_date", models.DateField()),
                ("ee_payment_date", models.DateField(blank=True, null=True)),
                ("ee_ex_estimated", models.BooleanField(default=False)),
                ("ee_payment_estimated", models.BooleanField(default=False)),
                (
                    "ee_etf",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="mytools.etf"
                    ),
                ),
            ],
            options={
                "db_table": "etf_events",
                "unique_together": {("ee_etf", "ee_ex_date")},
            },
        ),
    ]
