# Generated by Django 5.2.6 on 2025-12-29 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mytools", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="etf",
            name="ef_pay_lag_days",
            field=models.IntegerField(default=0),
        ),
    ]
