# Generated by Django 5.2.6 on 2026-01-02 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mytools", "0002_etf_ef_pay_lag_days"),
    ]

    operations = [
        migrations.AddField(
            model_name="etf",
            name="ef_currency",
            field=models.CharField(
                blank=True,
                choices=[("pound", "Pound"), ("dollar", "Dollar")],
                default=None,
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="etfeven",
            name="ee_pay_per_share",
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="etf",
            name="ef_distribution",
            field=models.CharField(
                choices=[("monthly", "Monthly"), ("quarterly", "Quarterly")],
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="etfeven",
            name="ee_etf",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events",
                to="mytools.etf",
            ),
        ),
        migrations.AlterField(
            model_name="etfshare",
            name="efs_ef",
            field=models.ForeignKey(
                db_column="efs_ef_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shares",
                to="mytools.etf",
            ),
        ),
    ]
