# Generated by Django 5.2.6 on 2026-01-02 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mytools", "0003_etf_ef_currency_etfeven_ee_pay_per_share_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="etf",
            name="ef_currency",
            field=models.CharField(
                choices=[("pound", "Pound"), ("dollar", "Dollar")], max_length=255
            ),
        ),
    ]
