# Generated by Django 5.2.6 on 2026-01-02 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mytools", "0004_alter_etf_ef_currency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="etfeven",
            name="ee_pay_per_share",
            field=models.DecimalField(
                blank=True, decimal_places=8, default=None, max_digits=20, null=True
            ),
        ),
        migrations.AlterField(
            model_name="etfshare",
            name="efs_amount",
            field=models.DecimalField(decimal_places=8, max_digits=20),
        ),
        migrations.AlterField(
            model_name="etfshare",
            name="efs_total_price",
            field=models.DecimalField(decimal_places=8, max_digits=20),
        ),
    ]
