# Generated by Django 5.2.6 on 2026-01-03 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mytools", "0005_alter_etfeven_ee_pay_per_share_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="EtfEven",
            new_name="EtfEvent",
        ),
    ]
