# Generated by Django 5.2.6 on 2026-01-03 13:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mytools", "0006_rename_etfeven_etfevent"),
    ]

    operations = [
        migrations.AddField(
            model_name="etfevent",
            name="ee_created",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
