# Generated by Django 5.2.6 on 2026-01-03 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mytools", "0007_etfevent_ee_created"),
    ]

    operations = [
        migrations.RenameField(
            model_name="etfevent",
            old_name="ee_created",
            new_name="ee_created_on",
        ),
        migrations.RenameField(
            model_name="etfshare",
            old_name="efs_created_at",
            new_name="efs_created_on",
        ),
    ]
