# Generated by Django 4.2.11 on 2026-01-03 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytools', '0008_rename_ee_created_etfevent_ee_created_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etf',
            name='ef_symbol',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
