# Generated by Django 4.2.11 on 2026-01-04 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mytools", "0009_alter_etf_ef_symbol"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="etf",
            name="ef_currency",
        ),
    ]
