# Generated by Django 4.2.11 on 2026-01-10 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mytools", "0010_remove_etf_ef_currency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="etf",
            name="ef_distribution",
            field=models.CharField(
                blank=True,
                choices=[
                    ("monthly", "Monthly"),
                    ("quarterly", "Quarterly"),
                    ("semi-annually", "Semi-Annually"),
                    ("annually", "Annually"),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="etf",
            name="ef_isin",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
