# Generated by Django 4.2.11 on 2026-02-13 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mytools", "0011_alter_etf_ef_distribution_alter_etf_ef_isin"),
    ]

    operations = [
        migrations.AddField(
            model_name="etf",
            name="ef_divident_type",
            field=models.CharField(
                choices=[
                    ("distributing", "Distributing"),
                    ("accumulating", "Accumulating"),
                ],
                max_length=255,
                null=True,
            ),
        ),
    ]
