# Generated by Django 4.2.11 on 2026-04-04 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mytools", "0011_alter_etf_ef_distribution_alter_etf_ef_isin"),
    ]

    operations = [
        migrations.AddField(
            model_name="etfshare",
            name="etf_share",
            field=models.CharField(
                blank=True,
                choices=[("Divident", "divident"), ("Salary", "salary")],
                max_length=255,
                null=True,
            ),
        ),
    ]
