# Generated by Django 4.2.11 on 2026-04-04 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mytools", "0012_etf_ef_divident_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="etf",
            name="ef_divident_type",
        ),
        migrations.AddField(
            model_name="etfshare",
            name="etf_share",
            field=models.CharField(
                blank=True,
                choices=[("Divident", "divident"), ("Salary", "salary")],
                max_length=255,
                null=True,
            ),
        ),
    ]
