# Generated by Django 4.2.11 on 2026-04-04 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mytools", "0012_etf_ef_divident_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="etf",
            name="ef_divident_type",
        ),
    ]
