# Generated by Django 4.2.11 on 2026-05-16 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mytools", "0013_remove_etf_ef_divident_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="etfshare",
            name="ets_funds",
            field=models.CharField(
                blank=True,
                choices=[("salary", "Salary"), ("dividents", "Dividents")],
                max_length=255,
                null=True,
            ),
        ),
    ]
