# Generated by Django 4.2.11 on 2026-04-04 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mytools", "0012_etfshare_etf_share"),
        ("mytools", "0013_remove_etf_ef_divident_type_etfshare_etf_share"),
    ]

    operations = []
