# Generated by Django 4.2.11 on 2026-06-25 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mytools", "0014_etfshare_ets_funds"),
    ]

    operations = [
        migrations.CreateModel(
            name="InverterDataPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("idp_date", models.DateField(unique=True)),
                (
                    "idp_solar_generation_kwh",
                    models.FloatField(help_text="Energy generated by solar panels"),
                ),
                (
                    "idp_grid_export_kwh",
                    models.FloatField(help_text="Energy sent to the grid"),
                ),
                (
                    "idp_grid_import_kwh",
                    models.FloatField(help_text="Energy pulled from the grid"),
                ),
                (
                    "idp_home_consumption_kwh",
                    models.FloatField(help_text="Total energy used by the house"),
                ),
                ("idp_battery_charge_kwh", models.FloatField()),
                ("idp_battery_discharge_kwh", models.FloatField()),
            ],
            options={
                "db_table": "inverter_data_points",
            },
        ),
        migrations.CreateModel(
            name="TariffPeriod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tp_provider_name",
                    models.CharField(
                        help_text="e.g., Octopus, E.ON, OVO", max_length=255
                    ),
                ),
                (
                    "tp_tariff_name",
                    models.CharField(
                        help_text="e.g., Intelligent Go, Fixed v1", max_length=255
                    ),
                ),
                (
                    "tp_start_date",
                    models.DateField(help_text="When you started this tariff"),
                ),
                (
                    "tp_end_date",
                    models.DateField(
                        blank=True,
                        help_text="Leave blank if this is your current active tariff",
                        null=True,
                    ),
                ),
                (
                    "tp_standard_import_rate",
                    models.FloatField(help_text="Cost per kWh imported"),
                ),
                (
                    "tp_standard_export_rate",
                    models.FloatField(help_text="Payment per kWh exported"),
                ),
                (
                    "tp_has_variable_rates",
                    models.BooleanField(
                        default=False,
                        help_text="Check if rates change by hour or day/night",
                    ),
                ),
            ],
            options={
                "db_table": "tarif_periods",
            },
        ),
    ]
