# Generated by Django 4.2.11 on 2026-06-29 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mytools", "0015_inverterdatapoint_tariffperiod"),
    ]

    operations = [
        migrations.RenameField(
            model_name="etfshare",
            old_name="ets_funds",
            new_name="efs_funds",
        ),
    ]
