# Generated by Django 4.2.11 on 2026-07-01 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mytools", "0016_rename_ets_funds_etfshare_efs_funds"),
    ]

    operations = [
        migrations.AddField(
            model_name="tariffperiod",
            name="tp_standing_charge_rate",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
