# Generated by Django 4.2.11 on 2026-07-02 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mytools", "0017_tariffperiod_tp_standing_charge_rate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tariffperiod",
            name="tp_standard_export_rate",
            field=models.DecimalField(
                decimal_places=4, help_text="Payment per kWh exported", max_digits=6
            ),
        ),
        migrations.AlterField(
            model_name="tariffperiod",
            name="tp_standard_import_rate",
            field=models.DecimalField(
                decimal_places=4, help_text="Cost per kWh imported", max_digits=6
            ),
        ),
        migrations.AlterField(
            model_name="tariffperiod",
            name="tp_standing_charge_rate",
            field=models.DecimalField(decimal_places=4, max_digits=6),
        ),
    ]
