# Generated by Django 4.2.11 on 2026-07-07 13:29

import common.mixins.auto_str
from django.db import migrations, models
import django.db.models.deletion
import mytools.models.bill


class Migration(migrations.Migration):

    dependencies = [
        ("mytools", "0018_alter_tariffperiod_tp_standard_export_rate_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "b_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=mytools.models.bill.edf_upload_path,
                    ),
                ),
                ("b_date", models.DateField(blank=True, null=True, unique=True)),
                (
                    "b_provider",
                    models.CharField(
                        choices=[
                            ("OCTOPUS", "Octopus Energy"),
                            ("EDF", "EDF Energy"),
                            ("EON", "E.ON Next"),
                            ("OVO", "OVO Energy"),
                            ("BG", "British Gas"),
                        ],
                        default="EDF",
                        max_length=255,
                    ),
                ),
                (
                    "b_total_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Grand total you actually pay after subtracting SEG (£)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "b_gross_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="The pure total of what you used (£)",
                        max_digits=10,
                        null=True,
                    ),
                ),
            ],
            options={
                "db_table": "bills",
            },
            bases=(common.mixins.auto_str.AutoStrMixin, models.Model),
        ),
        migrations.AlterField(
            model_name="tariffperiod",
            name="tp_provider_name",
            field=models.CharField(
                choices=[
                    ("OCTOPUS", "Octopus Energy"),
                    ("EDF", "EDF Energy"),
                    ("EON", "E.ON Next"),
                    ("OVO", "OVO Energy"),
                    ("BG", "British Gas"),
                ],
                max_length=255,
            ),
        ),
        migrations.CreateModel(
            name="Seg",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("s_from_date", models.DateField()),
                ("s_to_date", models.DateField()),
                (
                    "s_kwh_used",
                    models.DecimalField(
                        decimal_places=4, help_text="Energy used in kWh", max_digits=10
                    ),
                ),
                (
                    "s_unit_rate",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Export rate in Pounds per kWh",
                        max_digits=7,
                    ),
                ),
                (
                    "s_total_cost",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total credit generated in Pounds",
                        max_digits=8,
                    ),
                ),
                (
                    "s_bill",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seg",
                        to="mytools.bill",
                    ),
                ),
            ],
            options={
                "db_table": "seg",
            },
            bases=(common.mixins.auto_str.AutoStrMixin, models.Model),
        ),
        migrations.CreateModel(
            name="Gas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("g_from_date", models.DateField()),
                ("g_to_date", models.DateField()),
                (
                    "g_kwh_used",
                    models.DecimalField(
                        decimal_places=4, help_text="Energy used in kWh", max_digits=10
                    ),
                ),
                (
                    "g_unit_rate",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Rate in Pounds per kWh",
                        max_digits=7,
                    ),
                ),
                (
                    "g_subtotal_before_vat",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "g_standing_charge_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Daily charge in Pounds",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "g_standing_charge_total",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Total standing charge in Pounds",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "g_total_cost",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total gas cost in Pounds",
                        max_digits=8,
                    ),
                ),
                (
                    "g_bill",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gas",
                        to="mytools.bill",
                    ),
                ),
            ],
            options={
                "db_table": "gas",
            },
            bases=(common.mixins.auto_str.AutoStrMixin, models.Model),
        ),
        migrations.CreateModel(
            name="Electricity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("e_from_date", models.DateField()),
                ("e_to_date", models.DateField()),
                (
                    "e_kwh_used",
                    models.DecimalField(
                        decimal_places=4, help_text="Energy used in kWh", max_digits=10
                    ),
                ),
                ("e_unit_rate", models.DecimalField(decimal_places=4, max_digits=6)),
                ("e_total_cost", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "e_subtotal_before_vat",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "e_standing_charge_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Daily charge in Pounds",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "e_standing_charge_total",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "e_bill",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="mytools.bill",
                    ),
                ),
            ],
            options={
                "db_table": "electricity",
            },
            bases=(common.mixins.auto_str.AutoStrMixin, models.Model),
        ),
    ]
