# Generated by Django 4.2.11 on 2026-07-03 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mytools", "0019_bill_alter_tariffperiod_tp_provider_name_seg_gas_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="gas",
            old_name="g_standing_charge",
            new_name="g_standing_charge_rate",
        ),
        migrations.AddField(
            model_name="electricity",
            name="e_standing_charge_rate",
            field=models.DecimalField(
                decimal_places=4,
                default=0,
                help_text="Daily charge in Pounds",
                max_digits=6,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="bill",
            name="b_provider",
            field=models.CharField(
                choices=[
                    ("OCTOPUS", "Octopus Energy"),
                    ("EDF", "EDF Energy"),
                    ("EON", "E.ON Next"),
                    ("OVO", "OVO Energy"),
                    ("BG", "British Gas"),
                ],
                default="EDF",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="electricity",
            name="e_kwh_used",
            field=models.DecimalField(
                decimal_places=4, help_text="Energy used in kWh", max_digits=10
            ),
        ),
        migrations.AlterField(
            model_name="gas",
            name="g_kwh_used",
            field=models.DecimalField(
                decimal_places=4, help_text="Energy used in kWh", max_digits=10
            ),
        ),
        migrations.AlterField(
            model_name="seg",
            name="s_kwh_exported",
            field=models.DecimalField(
                decimal_places=4, help_text="Energy used in kWh", max_digits=10
            ),
        ),
    ]
