# Generated by Django 4.2.11 on 2026-07-20 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mytools", "0019_bill_alter_tariffperiod_tp_provider_name_seg_gas_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="electricity",
            name="e_bill",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="electricity",
                to="mytools.bill",
            ),
        ),
        migrations.AlterField(
            model_name="gas",
            name="g_bill",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="gas",
                to="mytools.bill",
            ),
        ),
        migrations.AlterField(
            model_name="seg",
            name="s_bill",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="seg",
                to="mytools.bill",
            ),
        ),
    ]
