# Generated by Django 4.2.11 on 2026-07-25 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mytools", "0020_alter_electricity_e_bill_alter_gas_g_bill_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bill",
            name="b_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
