# Generated by Django 4.2.11 on 2026-07-28 16:45

import common.mixins.auto_str
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mytools", "0021_alter_bill_b_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChargePointHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cph_kwh",
                    models.DecimalField(
                        decimal_places=8, help_text="kWh charged", max_digits=20
                    ),
                ),
                (
                    "cph_solar_kwh",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Estimated kWh supplied by solar panels",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "cph_grid_kwh",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Estimated kWh imported from grid",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "cph_battery_kwh",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="kWh supplied to EV via home battery discharge",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "cph_start_meter_kwh",
                    models.DecimalField(decimal_places=8, max_digits=20),
                ),
                (
                    "cph_end_meter_kwh",
                    models.DecimalField(decimal_places=8, max_digits=20),
                ),
                (
                    "cph_net_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Actual out-of-pocket cost for this charge session after self-generation/credits (£)",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "cph_feed_in_loss",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Opportunity cost of using self-generated energy instead of exporting via SEG (£)",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "cph_gross_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=8,
                        help_text="Cost if 100% of charge came from grid",
                        max_digits=20,
                        null=True,
                    ),
                ),
                ("cph_started_at", models.DateTimeField()),
                ("cph_completed_at", models.DateTimeField()),
                ("cph_created_at", models.DateTimeField()),
                ("cph_state", models.CharField(max_length=255)),
                (
                    "cph_export_tariff",
                    models.ForeignKey(
                        blank=True,
                        help_text="The SEG / Export Tariff active during this session",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="export_charge_sessions",
                        to="mytools.tariffperiod",
                    ),
                ),
                (
                    "cph_import_tariff",
                    models.ForeignKey(
                        blank=True,
                        help_text="The Import Tariff active during this session",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="import_charge_sessions",
                        to="mytools.tariffperiod",
                    ),
                ),
            ],
            options={
                "db_table": "charge_point_history",
            },
            bases=(common.mixins.auto_str.AutoStrMixin, models.Model),
        ),
    ]
