# Generated by Django 4.2.11 on 2026-08-07 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mytools", "0022_chargepointhistory"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bill",
            old_name="b_total_cost",
            new_name="b_net_cost",
        ),
    ]
