# Generated by Django 4.2.11 on 2026-08-18 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mytools", "0023_rename_b_total_cost_bill_b_net_cost"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "v_vin",
                    models.CharField(
                        max_length=255, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("v_name", models.CharField(blank=True, max_length=50, null=True)),
                ("v_make", models.CharField(max_length=50)),
                ("v_model", models.CharField(max_length=50)),
                ("v_year", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "v_fuel_type",
                    models.CharField(
                        choices=[
                            ("PETROL", "Petrol"),
                            ("DIESEL", "Diesel"),
                            ("BEV", "Battery Electric"),
                            ("PHEV", "Plug-in Hybrid "),
                            ("HYBRID", "Full Hybrid"),
                        ],
                        default="PHEV",
                        help_text="Primary fuel setup (Petrol, Diesel, BEV, PHEV)",
                        max_length=10,
                    ),
                ),
                (
                    "v_baseline_ice_mpg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Baseline ICE fuel efficiency in MPG (Petrol/Diesel equivalent)",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "v_baseline_ev_mi_per_kwh",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Baseline EV efficiency in mi/kWh",
                        max_digits=4,
                        null=True,
                    ),
                ),
            ],
            options={
                "db_table": "vehicles",
            },
        ),
    ]
