# Generated by Django 4.2.11 on 2026-10-02 15:43

import common.mixins.auto_str
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mytools", "0023_rename_b_total_cost_bill_b_net_cost"),
    ]

    operations = [
        migrations.CreateModel(
            name="BillingCycle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("cycle_day", models.PositiveSmallIntegerField()),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("monthly", "Monthly"),
                            ("yearly", "Yearly"),
                            ("weekly", "Weekly"),
                            ("daily", "Daily"),
                            ("quarterly", "Quarterly"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[("electricity", "Electricity"), ("gas", "Gas")],
                        max_length=255,
                    ),
                ),
            ],
            bases=(common.mixins.auto_str.AutoStrMixin, models.Model),
        ),
    ]
