# Generated by Django 4.2.11 on 2026-08-18 16:51

import common.mixins.auto_str
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mytools", "0024_vehicle"),
    ]

    operations = [
        migrations.CreateModel(
            name="VehicleTelemetryLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vtl_timestamp",
                    models.DateTimeField(
                        help_text="UTC timestamp of the telemetry row"
                    ),
                ),
                (
                    "vtl_odometer_km",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Current vehicle odemeter",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "vtl_remaining_electric_range_km",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Last remaining range in km",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "vtl_latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Location latitude",
                        max_digits=9,
                        null=True,
                    ),
                ),
                (
                    "vtl_longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Location longitude",
                        max_digits=9,
                        null=True,
                    ),
                ),
                (
                    "vtl_vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="telemetry_logs",
                        to="mytools.vehicle",
                    ),
                ),
            ],
            options={
                "db_table": "vehicle_telemetry_logs",
                "ordering": ["-vtl_timestamp"],
            },
            bases=(common.mixins.auto_str.AutoStrMixin, models.Model),
        ),
        migrations.CreateModel(
            name="VehicleTrip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vt_started_at", models.DateTimeField()),
                ("vt_ended_at", models.DateTimeField()),
                (
                    "vt_distance_miles",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "vt_electric_miles",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "vt_fuel_miles",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "vt_net_savings",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "vt_end_log",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="trip_ends",
                        to="mytools.vehicletelemetrylog",
                    ),
                ),
                (
                    "vt_start_log",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="trip_starts",
                        to="mytools.vehicletelemetrylog",
                    ),
                ),
                (
                    "vt_vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trips",
                        to="mytools.vehicle",
                    ),
                ),
            ],
            options={
                "db_table": "vehicle_trips",
                "ordering": ["-vt_started_at"],
            },
            bases=(common.mixins.auto_str.AutoStrMixin, models.Model),
        ),
        migrations.AddIndex(
            model_name="vehicletelemetrylog",
            index=models.Index(
                fields=["vtl_vehicle", "vtl_timestamp"],
                name="vehicle_tel_vtl_veh_a8d860_idx",
            ),
        ),
    ]
