# Generated by Django 4.2.11 on 2026-08-18 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mytools", "0025_vehicletelemetrylog_vehicletrip_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="v_is_active",
            field=models.BooleanField(default=True),
        ),
    ]
