# Generated by Django 4.2.11 on 2026-10-04 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mytools", "0025_alter_tariffperiod_tp_standard_import_rate"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="billingcycle",
            table="billing_cycles",
        ),
        migrations.AlterModelTable(
            name="electricity",
            table="electricity_bills",
        ),
        migrations.AlterModelTable(
            name="gas",
            table="gas_bill",
        ),
        migrations.AlterModelTable(
            name="seg",
            table="seg_bill",
        ),
    ]
