# Generated by Django 4.2.11 on 2026-08-18 16:57

import common.mixins.auto_str
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mytools", "0026_vehicle_v_is_active"),
    ]

    operations = [
        migrations.CreateModel(
            name="BMWCarDataEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bcde_vin", models.CharField(db_index=True, max_length=17)),
                (
                    "bcde_timestamp",
                    models.DateTimeField(help_text="UTC timestamp when event occurred"),
                ),
                (
                    "bcde_source",
                    models.CharField(
                        choices=[
                            ("CSV_ARCHIVE", "CSV Archive Export"),
                            ("REST_API", "REST API Snapshot"),
                            ("MQTT_STREAM", "Live MQTT Stream"),
                        ],
                        default="CSV_ARCHIVE",
                        max_length=20,
                    ),
                ),
                (
                    "bcde_payload",
                    models.JSONField(
                        help_text="Unmodified raw JSON event data or converted CSV row key-values"
                    ),
                ),
                (
                    "bcde_processed",
                    models.BooleanField(
                        default=False,
                        help_text="True if this raw event has been parsed into derived models",
                    ),
                ),
                ("bcde_processed_at", models.DateTimeField(blank=True, null=True)),
                ("bcde_created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "bmw_cardata_events",
                "ordering": ["bcde_timestamp"],
                "indexes": [
                    models.Index(
                        fields=["bcde_vin", "bcde_timestamp"],
                        name="bmw_cardata_bcde_vi_bfbbfa_idx",
                    ),
                    models.Index(
                        fields=["bcde_source", "bcde_processed"],
                        name="bmw_cardata_bcde_so_3de709_idx",
                    ),
                ],
            },
            bases=(common.mixins.auto_str.AutoStrMixin, models.Model),
        ),
    ]
