# Generated by Django 4.2.11 on 2026-10-05 14:46

import common.mixins.auto_str
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mytools", "0026_alter_billingcycle_table_alter_electricity_table_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnnualEnergySummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveIntegerField()),
                ("last_proccessed_month", models.PositiveSmallIntegerField(default=0)),
                (
                    "grid_import_kwh",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        help_text="Total grid import in kWh for the year",
                        max_digits=10,
                    ),
                ),
                (
                    "grid_export_kwh",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        help_text="Total grid export in kWh for the year",
                        max_digits=10,
                    ),
                ),
                (
                    "home_consumption_kwh",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        help_text="Total energy the home consumed",
                        max_digits=10,
                    ),
                ),
                (
                    "total_exported_revenue",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total revenue from exported energy for the year",
                        max_digits=10,
                    ),
                ),
                (
                    "savings",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total savings for the year",
                        max_digits=10,
                    ),
                ),
                (
                    "total_gross_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total estimated cost without solar panels",
                        max_digits=10,
                    ),
                ),
                (
                    "total_net_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total cost of the bought energy",
                        max_digits=10,
                    ),
                ),
            ],
            options={
                "db_table": "annual_energy_summarys",
            },
            bases=(common.mixins.auto_str.AutoStrMixin, models.Model),
        ),
        migrations.RenameModel(
            old_name="Electricity",
            new_name="ElectricityBill",
        ),
        migrations.RenameModel(
            old_name="Seg",
            new_name="SegBill",
        ),
    ]
