# Generated by Django 4.2.11 on 2026-10-05 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mytools", "0027_annualenergysummary_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inverterdatapoint",
            name="idp_battery_charge_kwh",
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
        migrations.AlterField(
            model_name="inverterdatapoint",
            name="idp_battery_discharge_kwh",
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
        migrations.AlterField(
            model_name="inverterdatapoint",
            name="idp_grid_export_kwh",
            field=models.DecimalField(
                decimal_places=4, help_text="Energy sent to the grid", max_digits=10
            ),
        ),
        migrations.AlterField(
            model_name="inverterdatapoint",
            name="idp_grid_import_kwh",
            field=models.DecimalField(
                decimal_places=4, help_text="Energy pulled from the grid", max_digits=10
            ),
        ),
        migrations.AlterField(
            model_name="inverterdatapoint",
            name="idp_home_consumption_kwh",
            field=models.DecimalField(
                decimal_places=4,
                help_text="Total energy used by the house",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="inverterdatapoint",
            name="idp_solar_generation_kwh",
            field=models.DecimalField(
                decimal_places=4,
                help_text="Energy generated by solar panels",
                max_digits=10,
            ),
        ),
    ]
